name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish Portable
      run: |
        dotnet publish -p:PublishProfile=MacOS
    - name: Upload Portable
      uses: actions/upload-artifact@v2
      with:
        name: JRPG.NET.Portable
        path: |
          bin/Release/netstandard2.0/JRPG.NET.dll
          bin/Release/netstandard2.0/JRPG.NET.pdb
